name: Deploy PHP App to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY_URL: ghcr.io
  DOCKER_IMAGE_NAME: php-game
  CONTAINER_APP_NAME: php-game-container
  RESOURCE_GROUP: php-game-group

jobs:
  jobs:
    Run-Tests:
      runs-on: ubuntu-latest
      name: Run PHPUnit Tests
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.4' # or whatever version you're using
            extensions: pdo, pdo_mysql
            tools: phpunit

        - name: Install Dependencies
          run: composer install --no-progress --prefer-dist

        - name: Run PHPUnit
          run: vendor/bin/phpunit tests
  Build-Docker-Image:
    runs-on: ubuntu-latest
    name: Build image and push to GitHub Container Registry
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push PHP Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Uses your PHP Dockerfile in the root directory
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_REGISTRY_URL }}/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  Deploy-to-Azure-Container-Apps:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    name: Deploy PHP container to Azure Container Apps
    steps:
      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.IMAGE_REGISTRY_URL }}/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          registryUrl: ${{ env.IMAGE_REGISTRY_URL }}
          registryPassword: ${{ secrets.CR_PAT }}
          registryUsername: wfarat
          environmentVariables: DB_HOST=php-game-mysql.mysql.database.azure.com DB_USER=wfarat DB_PASS=${{ secrets.DB_PASSWORD }} DB_NAME=game DB_PORT=3306 SENDGRID_API_KEY=${{ secrets.EMAIL_API_KEY }}

      - name: Logout from Azure
        run: az logout
